### ISSUE TITLE
SiteXSpec: change sum(Percent_Cover) to mean(Percent_Cover)

### ISSUE THREAD

**Issue by KateMMiller** [NCRN/NPSForVeg#82]
For values=size, and group=herbs, change the function from sum(Percent_Cover) to mean(Percent_Cover). 

Does that work for everyone, or would you all prefer to stick with sum?

**Comment by sjperles** [comment]
I am fine with mean instead of sum. Clear documentation should help clarify
the distinctions.

On Mar 5, 2018, at 3:59 PM, Kate Miller <notifications@github.com> wrote:

For values=size, and group=herbs, change the function from
sum(Percent_Cover) to mean(Percent_Cover).

Does that work for everyone, or would you all prefer to stick with sum?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NCRN/NPSForVeg/issues/82>, or mute the thread

**Comment by johnpauls** [comment]
I agree. Also we should consider variants of SiteXSpec that break things down below the plot level - that is where the "sites" will be microplots, quadrats or transects.

**Comment by lizmatthews03** [comment]
I'm okay with this change too...just food for thought: I suppose we could
leave the sum functionality and just add mean as an option? That might be
good for backwards compatibility for folks that have been using our
visualizer. Probably not a big deal if we don't maintain the sum option,
but thought I'd throw that out there...

~Liz

**Comment by KateMMiller** [comment]
Instead of changing the function to mean(Percent_Cover), I think it will be better to go the direction JP suggested, which is to sum(Percent_Cover) then divide by the number of quadrats or microplots, depending on the metrics. I'm updating the code I use to compile the NETN and MIDN data for the NPSForVeg package. In the process, I'm adding columns the Events.csv file to include number of quadrats and microplots sampled for each event. That should give us the denominator to correctly calculate the average cover, or sapling density on plots missing samples, right? I'll send the updated Events.csv for folks to look at once I finish it.

**Comment by johnpauls** [comment]
I had been thinking that maybe we needed to add a slot that would record missing data - eg it would have Plot, Year (I am assuming one event per year), data type (e.g seedling or herb or whaterver) and then an indication of the microrplot/quadrat/transect/whatever that was missed. I had not thought about adding it to the events table. I am curious to see what you come up with.
